version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${IMAGE_REPO_URI%/*}
      - cd backend/users-microservice
      - chmod +x mvnw || true
      - ./mvnw -q -DskipTests package
  build:
    commands:
      - docker build -f dockerfile -t $IMAGE_REPO_URI:latest .
      - IMAGE_TAG=v$(date +%Y%m%d%H%M%S)
      - docker tag $IMAGE_REPO_URI:latest $IMAGE_REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $IMAGE_REPO_URI:latest
      - docker push $IMAGE_REPO_URI:$IMAGE_TAG
      - printf '[{"name":"users-microservice","imageUri":"%s"}]' "$IMAGE_REPO_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - target/**/*
  base-directory: backend/users-microservice
  discard-paths: yes
