FROM public.ecr.aws/docker/library/openjdk:17-jdk-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends wget \
    && rm -rf /var/lib/apt/lists/*
VOLUME /tmp 
COPY target/photo-albums-0.0.1-SNAPSHOT.jar photo-albums-microservice.jar 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/photo-albums-microservice.jar"] 
